// Auto-generated by pdf_merger_indywidualny.py — do not edit manually
const PETITUM_CONFIG = {
  "petitumStartPage": 96,
  "closingStartPage": 106,
  "totalPages": 107,
  "items": [
    {
      "code": "AK-1",
      "text": "Zobowiązanie inwestora do wykonania odrębnego modelowania akustycznego buspasa jako samodzielnej linii źródłowej z własnymi parametrami emisji (typ pojazdów, prędkość, natężenie, profil dobowy)."
    },
    {
      "code": "AK-2",
      "text": "Zobowiązanie inwestora do wyjaśnienia i skorygowania niespójności w prognozie ruchu autobusowego, w której identyczna liczba 308 autobusów dziennie i 34 nocą jest przyjmowana zarówno dla roku 2030, jak i 2034 — pomimo że cel inwestycji zakłada wzrost atrakcyjności transportu autobusowego."
    },
    {
      "code": "AK-3",
      "text": "Zobowiązanie inwestora do zaprojektowania ekranów akustycznych lub innych zabezpieczeń po stronie prawej trasy, w szczególności w rejonie receptora 1* (km 3+950), gdzie przekroczenia norm hałasu sięgają 9 dB(A) w dzień i 11 dB(A) w nocy."
    },
    {
      "code": "AK-4",
      "text": "Przeprowadzenie analizy skuteczności ekranów akustycznych dla wyższych kondygnacji budynków wielorodzinnych i zaprojektowanie dodatkowych środków ochrony dla wyższych kondygnacji."
    },
    {
      "code": "AK-5",
      "text": "Wykonanie analizy poziomu maksymalnego hałasu LAmax dla pojedynczych przejazdów autobusów w porze nocnej, z odniesieniem do progów zaburzeń snu wg wytycznych WHO."
    },
    {
      "code": "AK-6",
      "text": "Przeprowadzenie kampanii pomiarów akustycznych stanu istniejącego w co najmniej 10 punktach wzdłuż trasy, obejmujących cykl co najmniej 7-dniowy."
    },
    {
      "code": "AK-7",
      "text": "Wykonanie analizy widmowej hałasu w paśmie niskich częstotliwości 20-200 Hz, z uwzględnieniem tłumienia przez przegrody budowlane budynków przy trasie."
    },
    {
      "code": "AK-8",
      "text": "Wykonanie analizy oddziaływania drgań generowanych przez przejazdy autobusów (12-18 ton) na budynki w strefie oddziaływania, z uwzględnieniem specyfiki gruntów niespoistych."
    },
    {
      "code": "AK-9",
      "text": "Wykonanie analizy wrażliwości modelu akustycznego na scenariusze zwiększonej częstotliwości kursowania autobusów: +25%, +50% i +100% w stosunku do prognozy bazowej."
    },
    {
      "code": "AK-10",
      "text": "Zastosowanie ekranów akustycznych o klasie pochłaniania dźwięku co najmniej A4 (DLα ≥ 11 dB) zamiast minimalnej A3 (DLα ≥ 8 dB)."
    },
    {
      "code": "AK-11",
      "text": "Przedstawienie analizy techniczno-ekonomicznej zastosowania nawierzchni o obniżonej emisji hałasu (SMA LA, BBTM, nawierzchnia poroelastyczna) na buspasie i jezdni głównej."
    },
    {
      "code": "AK-12",
      "text": "Wykonanie analizy kumulacji hałasu z buspasa z innymi źródłami w otoczeniu inwestycji, w tym z ruchem kolejowym na linii nr 250, ruchem na al. Grunwaldzkiej i odgłosami z Ogrodu Zoologicznego."
    },
    {
      "code": "AK-13",
      "text": "Przedstawienie wyników modelowania akustycznego z uwzględnieniem niepewności ±2 dB i zastosowanie podejścia ostrożnościowego dla receptorów z marginesem do wartości dopuszczalnych mniejszym niż 2 dB."
    },
    {
      "code": "AK-14",
      "text": "Pełne ujawnienie źródła danych prognozy ruchu, zastosowanej metodyki prognozowania i przyjętych założeń wzrostu, umożliwiające ich niezależną weryfikację."
    },
    {
      "code": "AK-15",
      "text": "Przedstawienie uzasadnienia przyjętej wartości 40% korzystnych warunków propagacji w porze nocnej, opartego na wieloletnich danych meteorologicznych z najbliższej stacji IMGW."
    },
    {
      "code": "AK-16",
      "text": "Objęcie osiedla Oliva Koncept — jako zabudowy wielorodzinnej bezpośrednio narażonej na skumulowane oddziaływanie akustyczne, wibracyjne i niskoczęstotliwościowe — pakietem środków kompensacyjnych obejmującym: (a) przeprowadzenie indywidualnego pomiaru akustycznego w budynkach osiedla (KIP zawiera pomiar tylko w 1 punkcie na 5,7 km trasy), (b) sfinansowanie wymiany filtrów wentylacji rekuperacyjnej w okresie budowy i przez 2 lata po jej zakończeniu (zwiększone zapylenie i spaliny z budowy przyspieszają zużycie filtrów istniejącej instalacji), (c) zainstalowanie stałej stacji monitoringu hałasu i drgań z publicznym dostępem do wyników online, (d) ustanowienie funduszu gwarancyjnego na naprawę ewentualnych szkód budowlanych."
    },
    {
      "code": "AK-17",
      "text": "Przedstawienie analizy wpływu ekranów akustycznych na nasłonecznienie lokali mieszkalnych na parterze i 1. piętrze osiedla Oliva Koncept, z uwzględnieniem wymagań § 60 rozporządzenia w sprawie warunków technicznych (minimum 3 godziny nasłonecznienia w dniach równonocy), oraz określenie specyfikacji materiałowej ekranów — ze wskazaniem na zastosowanie paneli transparentnych na odcinkach przylegających do zabudowy mieszkalnej w celu zachowania przepuszczalności światła i minimalizacji negatywnego wpływu na estetykę otoczenia i wartość nieruchomości."
    },
    {
      "code": "FL-1",
      "text": "Zobowiązanie inwestora do przeprowadzenia inwentaryzacji wiosennej flory naczyniowej (marzec--maj) ze szczególnym uwzględnieniem geofitów wczesnowiosennych."
    },
    {
      "code": "FL-2",
      "text": "Zobowiązanie inwestora do przeprowadzenia inwentaryzacji jesiennej (sierpień--październik) ze szczególnym uwzględnieniem gatunków storczykowatych (Orchidaceae)."
    },
    {
      "code": "FL-3",
      "text": "Zobowiązanie inwestora do jednoznacznego wyjaśnienia sprzeczności na str. 71 KIP między stwierdzonym zniszczeniem 3,7 ha siedlisk Natura 2000 a jednoczesnym wykluczeniem jakichkolwiek oddziaływań na tereny objęte ochroną."
    },
    {
      "code": "FL-4",
      "text": "Zobowiązanie inwestora do opracowania szczegółowego programu nasadzeń zastępczych w stosunku minimum 3:1 za 560 wycinanych drzew, tj. co najmniej 1680 drzew gatunków rodzimych, z harmonogramem, lokalizacją i planem pielęgnacji."
    },
    {
      "code": "FL-5",
      "text": "Zobowiązanie inwestora do opracowania planu kompensacji siedliskowej za zniszczenie 3,7 ha siedlisk Natura 2000 (grąd 9160, buczyna kwaśna 9110, buczyna żyzna 9130, łęg 91F0) w stosunku powierzchniowym co najmniej 1:1, z monitoringiem minimum 10-letnim."
    },
    {
      "code": "FL-6",
      "text": "Zobowiązanie inwestora do sporządzenia pełnej inwentaryzacji dendrologicznej 560 drzew obejmującej gatunek, obwód, wysokość, stan fitosanitarny, organizmy chronione i wartość odtworzeniową."
    },
    {
      "code": "FL-7",
      "text": "Zobowiązanie inwestora do opracowania indywidualnego planu ochrony pomnika przyrody (dąb szypułkowy, ok. 40 m od osi inwestycji) obejmującego strefę ochronną, monitoring i plan awaryjny."
    },
    {
      "code": "FL-8",
      "text": "Zobowiązanie inwestora do przeprowadzenia analizy ryzyka introdukcji gatunków inwazyjnych z mapowaniem istniejących stanowisk i programem eliminacji."
    },
    {
      "code": "FL-9",
      "text": "Zobowiązanie inwestora do przeprowadzenia szczegółowej analizy zgodności inwestycji z planem ochrony Trójmiejskiego Parku Krajobrazowego (uchwała Sejmiku Nr 583/XLVII/22 z dnia 24 października 2022 r.)."
    },
    {
      "code": "FL-10",
      "text": "Zobowiązanie inwestora do uzyskania decyzji derogacyjnych dla gatunków porostów ściśle chronionych (Ramalina fastigiata, Chrysothrix candelaris) oraz przeprowadzenia pełnej inwentaryzacji porostów na wszystkich 560 drzewach."
    },
    {
      "code": "FL-11",
      "text": "Zobowiązanie inwestora do poszerzenia analizy oddziaływania z 16,3 ha do rzeczywistej strefy oddziaływania (szacunkowo 50-80 ha) z uwzględnieniem efektu krawędzi (edge effect)."
    },
    {
      "code": "FL-12",
      "text": "Zobowiązanie inwestora do wyjaśnienia, na jakim etapie zaawansowania był projekt budowlany w momencie sporządzenia KIP i czy od tego czasu nastąpiły zmiany wpływające na ustalenia KIP."
    },
    {
      "code": "FL-13",
      "text": "Zobowiązanie inwestora do przeglądu 560 drzew pod kątem spełniania kryteriów drzew pomnikowych i sporządzenia stosownego wykazu przed wydaniem zezwolenia na wycinkę."
    },
    {
      "code": "FL-14",
      "text": "Przedstawienie w materiałach sprawy szczegółowego opisu metodyki kartowania fitosocjologicznego zastosowanej przy inwentaryzacji siedlisk Natura 2000."
    },
    {
      "code": "FL-15",
      "text": "Zobowiązanie inwestora do zaprojektowania i wykonania wielopiętrowego pasa zieleni izolacyjnej (drzewa, krzewy, pnącza) o szerokości co najmniej 15 metrów między trasą buspasa a zabudową osiedla Oliva Koncept, pełniącego funkcję bufora akustycznego, filtra powietrza i bariery wizualnej, z zapewnieniem wieloletniego utrzymania i pielęgnacji."
    },
    {
      "code": "FA-1",
      "text": "Zobowiązanie inwestora do przeprowadzenia inwentaryzacji faunistycznej obejmującej pełny cykl roczny (od kwietnia do marca roku następnego), ze szczególnym uwzględnieniem sezonu lęgowego ptaków (IV-VI), okresu rozrodu nietoperzy (V-VII) i migracji płazów (II-IV)."
    },
    {
      "code": "FA-2",
      "text": "Formalne odnotowanie w uzasadnieniu decyzji faktu, że KIP na stronach 36, 38 i 39 przyznaje niekompletność przeprowadzonych badań przyrodniczych, oraz wezwanie inwestora do uzupełnienia tych badań."
    },
    {
      "code": "FA-3",
      "text": "Zobowiązanie inwestora do przeprowadzenia inwentaryzacji zimowisk nietoperzy w okresie od listopada do marca w promieniu co najmniej 500 metrów od trasy inwestycji."
    },
    {
      "code": "FA-4",
      "text": "Zobowiązanie inwestora do przeprowadzenia pełnej oceny oddziaływania na obszar Natura 2000 \"Bunkier w Oliwie\" (PLH220055) zgodnie z art. 33 ustawy o ochronie przyrody i art. 6 ust. 3 dyrektywy siedliskowej."
    },
    {
      "code": "FA-5",
      "text": "Zobowiązanie inwestora do wykonania analizy wpływu oświetlenia drogowego buspasa na chiropterofaunę i entomofaunę, z uwzględnieniem typu opraw, temperatury barwowej, rozkładu widmowego i kierunkowości strumienia świetlnego."
    },
    {
      "code": "FA-6",
      "text": "Zobowiązanie inwestora do przeprowadzenia inwentaryzacji dziupli i mikrosiedlisk we wszystkich 560 drzewach przeznaczonych do wycinki, z zastosowaniem metody wizualnej i endoskopowej."
    },
    {
      "code": "FA-7",
      "text": "Zobowiązanie inwestora do wykonania analizy wpływu ekranów akustycznych (o wysokości do 6 m) jako bariery przelotowej dla nietoperzy i ptaków, z uwzględnieniem ryzyka kolizji i efektu fragmentacji szlaków przelotowych."
    },
    {
      "code": "FA-8",
      "text": "Zobowiązanie inwestora do uzupełnienia inwentaryzacji chiropterologicznej do spodziewanej dla tego typu siedlisk liczby gatunków (8-10), z zastosowaniem odłowów sieciowych i wielokrotnych kontroli detektorowych."
    },
    {
      "code": "FA-9",
      "text": "Zobowiązanie inwestora do przeprowadzenia kartowania awifauny lęgowej metodą kartograficzną (minimum 5 kontroli w okresie IV-VI) na obszarze inwestycji i w strefie 200 metrów."
    },
    {
      "code": "FA-10",
      "text": "Zobowiązanie inwestora do przeprowadzenia kartowania szlaków migracyjnych płazów w okresie od lutego do kwietnia, z zastosowaniem metody transektowej i barier kierujących."
    },
    {
      "code": "FA-11",
      "text": "Zobowiązanie inwestora do zaprojektowania przejść dla płazów (przepusty o średnicy min. 30 cm z systemem naprowadzania) w lokalizacjach wynikających z kartowania szlaków migracyjnych."
    },
    {
      "code": "FA-12",
      "text": "Zobowiązanie inwestora do zinwentaryzowania wszystkich zbiorników wodnych w promieniu 500 metrów od trasy inwestycji jako potencjalnych miejsc rozrodu płazów."
    },
    {
      "code": "FA-13",
      "text": "Zobowiązanie inwestora do przeprowadzenia analizy efektu bariery ekologicznej dla ssaków średnich (jeż, lis, kuna, dzik, borsuk) oraz do zaprojektowania przejść dolnych dla tych zwierząt."
    },
    {
      "code": "FA-14",
      "text": "Zobowiązanie inwestora do wycofania lub gruntownego przeformułowania stwierdzenia o braku oddziaływania na obszar Natura 2000 \"Bunkier w Oliwie\" (PLH220055), które jest bezpodstawne i sprzeczne z faktami przedstawionymi w samym KIP."
    },
    {
      "code": "FA-15",
      "text": "Zobowiązanie inwestora do zastosowania opraw oświetleniowych o temperaturze barwowej ≤ 2700 K (ciepłe światło) z pełną kierunkowością strumienia świetlnego (full cut-off), minimalizującą zanieczyszczenie świetlne w stosunku do budynków osiedla Oliva Koncept i siedlisk fauny nocnej."
    },
    {
      "code": "DR-1",
      "text": "Zobowiązanie inwestora do przeprowadzenia analizy bezpieczeństwa ruchu drogowego (BRD) wykazującej, że przyjęte minimalne parametry geometryczne drogi (szerokość pasów ruchu 3,0 m, buspas 3,0 m, pobocza 0,5–1,25 m) zapewniają bezpieczeństwo użytkowników z uwzględnieniem specyfiki ul. Spacerowej (łuki, niweleta, odcinki leśne, obecność autobusów przegubowych o długości 18 m) — a w przypadku gdy analiza tego nie potwierdzi — do przedstawienia wariantów projektowych godzących bezpieczeństwo użytkowników z minimalizacją ingerencji w środowisko (wycinka drzew, siedliska Natura 2000, szlaki migracyjne fauny)."
    },
    {
      "code": "DR-2",
      "text": "Zobowiązanie inwestora do wykonania analizy ruchu indukowanego i przesunięcia modalnego, obejmującej modelowanie transportowe z prognozą zmiany natężenia ruchu na ul. Spacerowej i trasach alternatywnych po uruchomieniu buspasów, w tym wyjaśnienie tożsamości prognoz liczby autobusów (342/dobę) w latach 2030 i 2034."
    },
    {
      "code": "DR-3",
      "text": "Zobowiązanie inwestora do przedstawienia szczegółowego projektu odwodnienia, zawierającego bilans wód opadowych, obliczenia hydrauliczne, lokalizację i parametry urządzeń podczyszczających, zbiorników retencyjnych i separatorów, a także analizę wpływu na Potok Rynarzewski i Potok Oliwski."
    },
    {
      "code": "DR-4",
      "text": "Zobowiązanie inwestora do opracowania i udostępnienia publicznego szczegółowej organizacji ruchu na czas budowy (18–24 miesiące), zawierającej warianty faz budowy z harmonogramem, mapę objazdów, plan komunikacji zastępczej, plan ruchu pieszego i rowerowego, harmonogram prac nocnych z oceną hałasu, ograniczenia tonażowe na drogach objazdowych oraz plan informowania mieszkańców."
    },
    {
      "code": "DR-5",
      "text": "Zobowiązanie inwestora do przedstawienia analizy wpływu fazy budowy na dostępność komunikacyjną, obejmującej czas dojazdu służb ratunkowych, dostępność szkół, plan mobilności dla osób starszych i niepełnosprawnych, warianty etapowania budowy minimalizujące uciążliwości oraz ocenę wpływu na dostępność gdańskiego zoo i Trójmiejskiego Parku Krajobrazowego."
    },
    {
      "code": "DR-6",
      "text": "Zobowiązanie inwestora do opracowania dedykowanego planu utrzymania dostępności komunikacyjnej osiedla Oliva Koncept na czas 18–24-miesięcznej budowy, gwarantującego czas dojazdu służb ratunkowych nieprzekraczający 15 minut, ciągłość komunikacji miejskiej (tymczasowy przystanek w odległości ≤ 300 m) oraz bezpieczne trasy dojścia do placówek oświatowych."
    },
    {
      "code": "DR-7",
      "text": "Zobowiązanie inwestora do uwzględnienia w projekcie budowy buspasa utworzenia dodatkowego przystanku autobusowego na żądanie w kierunku Osowej, na wysokości budynku przy ul. Spacerowej 15 — w celu poprawy skomunikowania osiedla Oliva Koncept z siecią transportu publicznego. Obecnie mieszkańcy osiedla nie mają w bezpośrednim sąsiedztwie przystanku umożliwiającego dojazd z kierunku Oliwy — linie 171 i 179 nie zatrzymują się przy ul. Karwieńskiej, linia 169 jedynie dojeżdża do zoo i skręca, a sezonowy autobus z pętli oliwskiej kursuje jedynie latem i z niewystarczającą częstotliwością. Najbliższym przystankiem pozostaje Dom Zarazy, co wymaga przejścia ok. 800 m — istotnej bariery szczególnie dla osób starszych, z niepełnosprawnościami i rodzin z dziećmi. Skoro inwestycja obejmuje przebudowę infrastruktury drogowej na tym odcinku, utworzenie dodatkowego przystanku stanowi minimalny i proporcjonalny środek kompensacyjny poprawiający dostępność komunikacyjną mieszkańców strefy oddziaływania."
    },
    {
      "code": "BU-1",
      "text": "Zobowiązanie inwestora do wykonania pełnej analizy wpływu drgań z robót budowlanych na budynki mieszkalne w strefie co najmniej 100 metrów od osi trasy, zgodnie z normą PN-B-02170:2016, obejmującej prognozę PPV, porównanie ze skalami SWD i ocenę ryzyka uszkodzeń."
    },
    {
      "code": "BU-2",
      "text": "Zobowiązanie inwestora do wykonania przeglądu stanu technicznego (stan „zerowy\") wszystkich budynków w promieniu co najmniej 50 metrów od trasy PRZED rozpoczęciem robót, obejmującego inwentaryzację fotograficzną spękań, pomiar geometrii i dokumentację stanu elementów budowlanych."
    },
    {
      "code": "BU-3",
      "text": "Zobowiązanie inwestora do wykonania analizy wpływu drgań budowlanych na grunty niespoiste (80% podłoża wg KIP, str. 27) pod kątem ryzyka upłynnienia i zagęszczania wibracyjnego, w oparciu o badania geotechniczne CPTu/DMT."
    },
    {
      "code": "BU-4",
      "text": "Zobowiązanie inwestora do wykonania szczegółowej analizy zagrożenia osuwiskowego (teren w obszarach zagrożonych osuwiskami wg KIP, str. 27, Rys. 3), obejmującej obliczenia stateczności skarp i plan monitoringu geotechnicznego."
    },
    {
      "code": "BU-5",
      "text": "Zobowiązanie inwestora do opracowania modelu hydrogeologicznego wpływu odwodnienia wykopów (pompy 50-80 m³/h wg KIP, str. 68) na poziom wód gruntowych i fundamenty budynków w otoczeniu inwestycji."
    },
    {
      "code": "BU-6",
      "text": "Zobowiązanie inwestora do opracowania bilansu wodnego terenu inwestycji (55 ha) i jej otoczenia -- w stanie przed i po realizacji przedsięwzięcia."
    },
    {
      "code": "BU-7",
      "text": "Zobowiązanie inwestora do rozszerzenia analizy izolacyjności akustycznej na wszystkie budynki w strefie oddziaływania, a nie tylko na jeden punkt receptorowy (nr 1, R'A2=38 dB, str. 132 KIP)."
    },
    {
      "code": "BU-8",
      "text": "Zobowiązanie inwestora do wykonania analizy nasłonecznienia dla budynków sąsiadujących z ekranami akustycznymi o wysokości 3-6 m (parametry wg tabeli 5.1 KIP, str. 125-126), ze sprawdzeniem wymogu minimum 3 godzin nasłonecznienia wg § 60 rozp. WT."
    },
    {
      "code": "BU-9",
      "text": "Zobowiązanie inwestora do wykonania analizy wpływu ekranów akustycznych na wentylację naturalną budynków mieszkalnych, z uwzględnieniem dominujących kierunków wiatru (KIP str. 28 -- sektor zachodni i południowo-zachodni)."
    },
    {
      "code": "BU-10",
      "text": "Zobowiązanie inwestora do przeprowadzenia analizy wpływu inwestycji na wartość nieruchomości w strefie oddziaływania, ze szczególnym uwzględnieniem budynków sąsiadujących z ekranami akustycznymi."
    },
    {
      "code": "BU-11",
      "text": "Zastąpienie w decyzji środowiskowej wszystkich sformułowań warunkowych typu „w miarę możliwości\", „o ile to technicznie wykonalne\", „unikać\" -- konkretnymi, bezwarunkowymi nakazami i zakazami, z określeniem sankcji za ich naruszenie."
    },
    {
      "code": "BU-12",
      "text": "Ustanowienie funduszu gwarancyjnego (depozyt bankowy lub polisa OC, kwota nie mniejsza niż 10 mln zł) na pokrycie kosztów napraw uszkodzeń budynków osiedla Oliva Koncept spowodowanych drganiami i osiadaniem gruntu, z wyznaczeniem niezależnego inspektora nadzoru wybranego w uzgodnieniu ze Wspólnotą Mieszkaniową."
    },
    {
      "code": "BU-13",
      "text": "Zobowiązanie inwestora do zlecenia niezależnej wyceny nieruchomości osiedla Oliva Koncept przed rozpoczęciem budowy oraz ustanowienia mechanizmu kompensacji spadku wartości nieruchomości."
    },
    {
      "code": "PR-1",
      "text": "Przeprowadzenie pełnych konsultacji społecznych z mieszkańcami osiedli położonych w strefie oddziaływania inwestycji, obejmujących spotkanie informacyjne, wyłożenie dokumentacji, możliwość składania uwag pisemnych i ustnych do protokołu, oraz -- w razie wniosku -- rozprawę administracyjną (art. 33 ust. 1 i art. 36 ustawy OOŚ w zw. z art. 6 Konwencji z Aarhus)."
    },
    {
      "code": "PR-2",
      "text": "Zobowiązanie inwestora do uzupełnienia KIP o pełną inwentaryzację zabudowy osiedla Oliva Koncept, włączenie budynków tego osiedla do modelu akustycznego i ponowne przeliczenie oddziaływania z uwzględnieniem rzeczywistej liczby mieszkańców (art. 7 i 77 par. 1 KPA w zw. z art. 66 ust. 1 pkt 5 ustawy OOŚ)."
    },
    {
      "code": "PR-3",
      "text": "Zapewnienie indywidualnych zawiadomień (listownych lub elektronicznych) właścicieli i użytkowników lokali w strefie do 100 m od granicy inwestycji -- lub co najmniej umieszczenie informacji na tablicach ogłoszeń wspólnot mieszkaniowych w strefie oddziaływania (art. 49 par. 1 KPA w zw. z art. 74 ust. 3 ustawy OOŚ i art. 10 par. 1 KPA)."
    },
    {
      "code": "PR-4",
      "text": "Zobowiązanie inwestora do przedstawienia szczegółowej analizy liczby osób zamieszkujących zabudowę wielorodzinną i jednorodzinną w strefie oddziaływania, z podaniem adresów budynków, liczby lokali, szacunkowej liczby mieszkańców i kondygnacji narażonych na przekroczenia norm hałasowych (art. 66 ust. 1 pkt 5 ustawy OOŚ w zw. z art. 8 Europejskiej Konwencji Praw Człowieka -- Hatton v. UK)."
    },
    {
      "code": "PR-5",
      "text": "Zobowiązanie inwestora do identyfikacji grup interesariuszy (mieszkańcy zabudowy wielorodzinnej, jednorodzinnej, użytkownicy TPK, osoby starsze i z niepełnosprawnościami, rodzice dzieci szkolnych, rowerzyści, odwiedzający zoo) z analizą ich specyficznych potrzeb i obaw (art. 33 ustawy OOŚ w zw. z art. 6 ust. 2 Konwencji z Aarhus)."
    },
    {
      "code": "PR-6",
      "text": "Zobowiązanie inwestora do przedstawienia informacji o źródłach finansowania inwestycji, szacunkowym kosztorysie z wyodrębnieniem kosztów środków ochrony środowiska, oraz harmonogramie realizacji z podziałem na etapy (art. 66 ust. 1 pkt 14 ustawy OOŚ w zw. z art. 7 KPA)."
    },
    {
      "code": "PR-7",
      "text": "Zobowiązanie inwestora do uzupełnienia analizy konfliktów społecznych (str. 141--142 KIP) o identyfikację ognisk konfliktów, analizę stanowisk rad dzielnic, opis wpływu na codzienne życie mieszkańców, propozycje mediacji i zarządzania konfliktem, oraz realistyczną ocenę prawdopodobieństwa wystąpienia konfliktów (art. 66 ust. 1 pkt 5 w zw. z art. 33 ust. 1 ustawy OOŚ)."
    },
    {
      "code": "PR-8",
      "text": "Zobowiązanie inwestora do powołania stałego biura informacyjnego dla mieszkańców strefy oddziaływania — ze szczególnym uwzględnieniem osiedla Oliva Koncept — funkcjonującego od dnia wszczęcia postępowania środowiskowego do końca budowy, zapewniającego bieżący dostęp do dokumentacji, harmonogramu prac i danych monitoringowych."
    },
    {
      "code": "AD-1",
      "text": "Stwierdzenie obowiązku przeprowadzenia pełnej oceny oddziaływania na środowisko i zobowiązanie inwestora do sporządzenia raportu o oddziaływaniu na środowisko, zgodnie z art. 63 ust. 1 w zw. z art. 59 ust. 1 pkt 2 i art. 66 ustawy OOŚ, z uwzględnieniem wszystkich braków dokumentacyjnych wskazanych w części I niniejszego pisma."
    },
    {
      "code": "AD-2",
      "text": "Przeprowadzenie i przedstawienie w uzasadnieniu decyzji szczegółowej analizy proporcjonalności wyłączenia ustaleń MPZP na terenie TPK przez specustawę ZRID, w rozumieniu art. 31 ust. 3 Konstytucji RP."
    },
    {
      "code": "AD-3",
      "text": "Zapewnienie uzyskania wiążącego uzgodnienia RDOŚ, obejmującego wpływ na SOO \"Bunkier w Oliwie,\" zniszczenie siedlisk i konieczność ewentualnych decyzji derogacyjnych."
    },
    {
      "code": "AD-4",
      "text": "Wskazanie w uzasadnieniu decyzji co najmniej czterech podstaw prawnych roszczeń odszkodowawczych przysługujących właścicielom nieruchomości w strefie oddziaływania (art. 129 POŚ, art. 36 upzp, art. 435 KC, art. 144 KC)."
    },
    {
      "code": "AD-5",
      "text": "Zobowiązanie inwestora do przedstawienia analizy zakresu planowanych wywłaszczeń, obejmującej wykaz działek, szacunkowe wartości odszkodowań, harmonogram procedury i informacje o prawach właścicieli."
    },
    {
      "code": "AD-6",
      "text": "Wyznaczenie rozprawy administracyjnej otwartej dla społeczeństwa, z udziałem inwestora, w godzinach popołudniowych, z 14-dniowym wyprzedzeniem."
    },
    {
      "code": "AD-7",
      "text": "Zobowiązanie inwestora do przedłożenia rzetelnej analizy wariantowej, obejmującej wariant zerowy, wariant proponowany, wariant z inną lokalizacją i wariant z buspasem wirtualnym."
    },
    {
      "code": "AD-8",
      "text": "Zastosowanie zasady przezorności (precautionary principle) we wszystkich aspektach, w których KIP wykazuje braki danych, zgodnie z wyrokiem TSUE C-127/02 Waddenzee."
    },
    {
      "code": "AD-9",
      "text": "Nałożenie na inwestora obowiązku monitoringu porealizacyjnego (hałas, drgania, przyroda, wody gruntowe, stabilność budynków) na okresy wskazane w części IX niniejszego pisma."
    },
    {
      "code": "AD-10",
      "text": "Udostępnienie pełnej dokumentacji KIP w formie elektronicznej (PDF z OCR, pliki .shp, pliki .xlsx, dane źródłowe modelowania) w terminie 14 dni od daty niniejszego pisma."
    },
    {
      "code": "AD-11",
      "text": "Objęcie osiedla Oliva Koncept dedykowanym, wieloletnim programem monitoringu porealizacyjnego (hałas, drgania, wody gruntowe, stabilność budynków) ze stałą stacją pomiarową hałasu z publicznym dostępem online do wyników, z obowiązkiem udostępniania danych Wspólnocie Mieszkaniowej w cyklu kwartalnym."
    }
  ]
};
